apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logto.configMapName" . }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
data:
  ENDPOINT: {{ .Values.coreEndpoint | quote }}
  ADMIN_ENDPOINT: {{ .Values.adminEndpoint | quote }}