apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logto.configMapName" . }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
data:
  ENDPOINT: {{ .Values.coreEndpoint | quote }}
  ADMIN_ENDPOINT: {{ .Values.adminEndpoint | quote }}
  {{- if .Values.tls.enabled }}
  HTTPS_CERT_PATH: "/etc/logto/tls/tls.crt"
  HTTPS_KEY_PATH: "/etc/logto/tls/tls.key"
  {{- end }}