apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logto.secretName" . }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
type: Opaque
data:
  TRUST_PROXY_HEADER: {{ .Values.trustProxyHeader | b64enc | quote }}
  DB_URL: {{ .Values.dbUrl | b64enc | quote }}