name: CICD-PUSH

on:
  push:
    paths:
      - "charts/**"
    branches:
      - '*'
      - '*/*'
    tags-ignore:
      - '*'

jobs:
  check-helm:
    uses: apecloud/apecloud-cd/.github/workflows/release-charts-check.yml@v0.1.38
    with:
      VERSION: "v0.7.0-check"
      CHART_DIR: "charts"
      APECD_REF: "v0.1.38"
    secrets: inherit
