name: Release Chart

on:
  workflow_dispatch:
    inputs:
      chart_dir:
        description: 'release specify chart dir or empty to release all'
        required: false
        default: ''
        type: choice
        options:
          - ""
          - bytebase
          - calico
          - cert-manager
          - chatgpt-retrieval-plugin
          - csi-hostpath-driver
          - csi-driver-nfs
          - csi-s3
          - jupyter-notebook
          - nyancat
          - logto
          - redash
      chart_version:
        description: 'release specify chart version or empty to release default'
        required: false
        default: ''

env:
  GH_TOKEN: ${{ github.token }}

run-name: Release Chart ${{ inputs.chart_dir }} ${{ inputs.chart_version }}

jobs:
  release-chart:
    uses: apecloud/apecloud-cd/.github/workflows/release-charts.yml@v0.1.40
    with:
      VERSION: "${{ inputs.chart_version }}"
      CHART_DIR: "charts"
      SPECIFY_CHART: "${{ inputs.chart_dir }}"
      APECD_REF: "v0.1.40"
    secrets: inherit
